name: test-contracts

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

## TODO: Add automations specifically to ensure:
##       - changes that affect storage are caught by CI
##       - (stretch) yarn fmt
##       - some level of security through automated static analysis (e.g, slither)
jobs:
  tests:
    name: Foundry Project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install
        working-directory: ./contracts

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests
        run: forge test -vvv
        working-directory: ./contracts

      - name: Run snapshot
        run: forge snapshot
        working-directory: ./contracts
